default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bryan
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  database: toy_app_database
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: toy_app_test

production:
  <<: *default
  database: toy_app_production
